package com.example.famMedical.Entity;

public enum NotificationType {
    APPOINTMENT_CREATED,
    APPOINTMENT_UPDATED,
    APPOINTMENT_CANCELLED,
    DOCTOR_REQUEST_CREATED,
    DOCTOR_REQUEST_ACCEPTED,
    DOCTOR_REQUEST_REJECTED,
    MEDICAL_RECORD_CREATED,
    MEDICAL_RECORD_UPDATED,
    NEW_MESSAGE
}
